/*globals define, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 0.1.0 from webgme on Thu Nov 26 2015 06:07:20 GMT-0600 (CST).
 */

define([
    'panels/EasyDAG/EasyDAGControl',
    './NotLoaded'
], function (
    EasyDAGControl,
    NOT_LOADED
) {

    'use strict';

    var ForgeFlowControl,
        ROOT_PATH = '';

    ForgeFlowControl = function (options) {
        EasyDAGControl.call(this, options);
        this._logger.debug('ctor finished');
    };

    _.extend(ForgeFlowControl.prototype, EasyDAGControl.prototype);

    ForgeFlowControl.prototype.selectedObjectChanged = function (nodeId) {
        this._widget.currentNodeId = nodeId;
        // Add the data node to the territory
        this._selfPatterns[''] = {children: 2};
        EasyDAGControl.prototype.selectedObjectChanged.call(this, nodeId);
    };

    ForgeFlowControl.prototype._getObjectDescriptor = function (nodeId) {
        var desc = EasyDAGControl.prototype._getObjectDescriptor.call(this, nodeId),
            node = this._client.getNode(nodeId),
            dataId,
            data;

        // Fail gracefully if not loaded
        if (!desc) {
            return NOT_LOADED;
        }

        // Add 'data' pointer if Input node
        if (desc.baseName && desc.baseName.toLowerCase() === 'input') {
            dataId = node.getPointer('data').to || null;
            data = dataId ? this._getObjectDescriptor(dataId) : null;
            desc.pointers = {
                data: data
            };
        }
        return desc;
    };

    ForgeFlowControl.prototype.onAddItem = function (nodeId) {
        // Create a unique id for the layer
        this._client.setAttributes(nodeId, 'name', `layer_${new Date().getTime()}`);
    };

    return ForgeFlowControl;
});
