// jshint node: true
// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');


// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push('src/plugins');
config.plugin.basePaths.push('node_modules/webgme-simple-nodes/src/plugins');
config.visualization.layout.basePaths.push('src/layouts');
config.visualization.layout.basePaths.push('node_modules/webgme-chflayout/src/layouts');
config.visualization.decoratorPaths.push('src/decorators');
config.seedProjects.basePaths.push('src/seeds/Minimal');


// Visualizer descriptors
config.visualization.visualizerDescriptors.push('./src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'CHFLayout': 'node_modules/webgme-chflayout/src/layouts/CHFLayout',
  'AutoViz': 'panels/AutoViz/AutoVizPanel',
  'EasyDAG': 'panels/EasyDAG/EasyDAGPanel',
  'TemplateCreator': 'node_modules/webgme-simple-nodes/src/plugins/TemplateCreator',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'panel/AutoViz': './node_modules/webgme-autoviz/src/visualizers/panels/AutoViz',
  'widget/AutoViz': './node_modules/webgme-autoviz/src/visualizers/widgets/AutoViz',
  'panels/EasyDAG': './node_modules/webgme-easydag/src/visualizers/panels/EasyDAG',
  'widgets/EasyDAG': './node_modules/webgme-easydag/src/visualizers/widgets/EasyDAG'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/deepforge';
validateConfig(config);
module.exports = config;
