/*globals define, WebGMEGlobal*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 0.1.0 from webgme on Wed Dec 23 2015 10:55:45 GMT-0600 (CST).
 */

define(['css!./styles/TrainedModelWidget.css'], function () {
    'use strict';

    var TrainedModelWidget,
        nop = function(){},
        WIDGET_CLASS = 'trained-model';

    TrainedModelWidget = function (logger, container) {
        this._logger = logger.fork('Widget');

        this.$el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    };

    TrainedModelWidget.prototype._initialize = function () {
        var width = this.$el.width(),
            height = this.$el.height(),
            msg = 'Click the red button to classify images'.toUpperCase(),
            self = this;

        // set widget class
        this.$el.addClass(WIDGET_CLASS);

        // Create a dummy header 
        this.backgroundTxt = $('<div>', {class: 'background-text text-center'});

        this.backgroundTxt.text(msg);
        this.$el.append(this.backgroundTxt);

        // Registering to events can be done with jQuery (as normal)
        this.$el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    TrainedModelWidget.prototype.onWidgetContainerResize = function (width, height) {
        this.backgroundTxt.css('top', height/2);
    };

    // Update these when this becomes more sophisticated
    TrainedModelWidget.prototype.addNode = nop;
    TrainedModelWidget.prototype.updateNode = nop;
    TrainedModelWidget.prototype.removeNode = nop;

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    TrainedModelWidget.prototype.destroy = function () {
    };

    TrainedModelWidget.prototype.onActivate = function () {
    };

    TrainedModelWidget.prototype.onDeactivate = function () {
    };

    return TrainedModelWidget;
});
