/*globals define, WebGMEGlobal*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 0.1.0 from webgme on Thu Nov 26 2015 06:07:20 GMT-0600 (CST).
 */

define([
    'widgets/EasyDAG/EasyDAGWidget',
    'css!./styles/ForgeFlowWidget.css'
], function (
    EasyDAGWidget
) {
    'use strict';

    var ForgeFlowWidget,
        WIDGET_CLASS = 'forge-flow';

    ForgeFlowWidget = function (logger, container) {
        EasyDAGWidget.call(this, logger, container);
        this.$el.addClass(WIDGET_CLASS);
        this._logger.debug('ctor finished');
    };

    // FIXME: ForgeFlow is using EasyDAG's decorators
    _.extend(ForgeFlowWidget.prototype, EasyDAGWidget.prototype);

    return ForgeFlowWidget;
});
